### ISSUE TITLE
Not an issue so much, but questions

### ISSUE THREAD

**Issue by marcvisconte** [wellbornbaba/python-web-scrapping#1]
Hi,

I just d/l'd the main script, and the pymy.py module.
I have just skimmed them, not read through them yet, but I'm interested in going through it.
It looks like this saves content to a (SQLite3) DB.

Would it be hard to convert it to save web pages in a local, browser-readable format?
Would it be hard to get it to convert the page/text/embedded graphics into PDF format?

I am interested in saving the chapter details of the free resources from Packt Publishing.
They used to provide their materials in d/l'able PDF or ereader formats.
Currently, they just present the materials in an online chapter/lesson format.

If you're not familiar with Packt, they have a free resource each day at 
[https://www.packtpub.com/free-learning](https://www.packtpub.com/free-learning) 
So, for instance, today's resources is 
_Free eBook: "Learn C# in 7 days"_

I have been printing the material a page (chapter/lesson) at a time, using a PDF printer utility to print to a local directory, but this is not a good way to do it... there's a good chance to mess up, between getting the settings right, getting the list of lessons w/in chapters, getting the names right, and repeating that for resource that might have 100 short pages is tiring.

1) I assume that your script can be re-purposed to save webpages (and css, images, tables, etc.) to local directories, w/ scriptable page-names.  I'll look into this first.
2) I will look at whether it would be easy to parse the material, page by page, and convert it to PDF (with scriptable page-names).  I tried to do that with Selenium, but I'm too new to be able to use that.

**Comment by wellbornbaba** [comment]
Yes is possible to save the files or convert to PDF I think there are some module that allow that. Secondly the contents are not save in DB, only the parsed found URL are saved into the DB which you can easily store in a list or dictionary.

All contents are stored locally to the specified folder

**Comment by marcvisconte** [comment]
Thank you!  I will try to go through the code maybe tonight after work.
